namespace DolphinDotNet.Compiler;
internal abstract record IrInstruction;
internal sealed record IrConstI4(int Value):IrInstruction;
internal sealed record IrLoadArg(int Index):IrInstruction;
internal sealed record IrLoadLocal(int Index):IrInstruction;
internal sealed record IrStoreLocal(int Index):IrInstruction;
internal sealed record IrNewObject(string TypeName,MethodKey Constructor,int ArgumentCount):IrInstruction;
internal sealed record IrLoadField(string TypeName,string FieldName):IrInstruction;
internal sealed record IrStoreField(string TypeName,string FieldName):IrInstruction;
internal sealed record IrCall(MethodKey Target,bool Virtual,int ArgumentCount,bool HasThis,bool ReturnsValue):IrInstruction;
internal sealed record IrStringLength:IrInstruction;
internal sealed record IrCompareGreaterThan:IrInstruction;
internal sealed record IrCompareEqual:IrInstruction;
internal sealed record IrAdd:IrInstruction; internal sealed record IrSub:IrInstruction; internal sealed record IrMul:IrInstruction;
internal sealed record IrDup:IrInstruction; internal sealed record IrPop:IrInstruction; internal sealed record IrReturn(bool HasValue):IrInstruction;
internal sealed record IrMethod(MethodKey Key,List<IrInstruction> Instructions,int LocalCount,int ParameterCount,bool HasThis,bool ReturnsValue);
