using System.Reflection.Metadata;
namespace DolphinDotNet.Compiler;
internal static class MetadataLoader{
 public static void LoadInto(CompilationModel model,MetadataReader md,string assemblyName){foreach(var th in md.TypeDefinitions){var type=md.GetTypeDefinition(th);var ns=md.GetString(type.Namespace);var name=md.GetString(type.Name);if(name=="<Module>")continue;var full=Full(ns,name);int offset=0;foreach(var fh in type.GetFields()){var f=md.GetFieldDefinition(fh);var isStatic=(f.Attributes&System.Reflection.FieldAttributes.Static)!=0;var(size,reference)=FieldLayout(md,f.Signature);var fn=md.GetString(f.Name);model.Fields[(full,fn)]=new(full,fn,isStatic?0:offset,reference,isStatic);if(!isStatic)offset+=Math.Max(4,size);}model.Types[full]=new(ns,name,full,ResolveTypeName(md,type.BaseType),offset);foreach(var mh in type.GetMethods()){var m=md.GetMethodDefinition(mh);var key=new MethodKey(full,md.GetString(m.Name),assemblyName,Convert.ToHexString(md.GetBlobBytes(m.Signature)));var sig=ReadMethodSignature(md,m.Signature);model.Methods[key]=new(key,mh,(m.Attributes&System.Reflection.MethodAttributes.Static)!=0,sig.Parameters,sig.ReturnsValue,assemblyName);}}}
 public static string? ResolveTypeName(MetadataReader md,EntityHandle h){if(h.IsNil)return null;if(h.Kind==HandleKind.TypeDefinition){var t=md.GetTypeDefinition((TypeDefinitionHandle)h);return Full(md.GetString(t.Namespace),md.GetString(t.Name));}if(h.Kind==HandleKind.TypeReference){var t=md.GetTypeReference((TypeReferenceHandle)h);return Full(md.GetString(t.Namespace),md.GetString(t.Name));}return null;}
 private static (int Parameters,bool ReturnsValue) ReadMethodSignature(MetadataReader md,BlobHandle sig){var r=md.GetBlobReader(sig);var h=r.ReadSignatureHeader();if(h.IsGeneric)r.ReadCompressedInteger();int p=r.ReadCompressedInteger();var ret=r.ReadSignatureTypeCode();return(p,ret!=SignatureTypeCode.Void);}
 private static(int Size,bool Reference)FieldLayout(MetadataReader md,BlobHandle sig){var r=md.GetBlobReader(sig);r.ReadSignatureHeader();var c=r.ReadSignatureTypeCode();return c switch{SignatureTypeCode.Boolean or SignatureTypeCode.Byte or SignatureTypeCode.SByte=>(1,false),SignatureTypeCode.Char or SignatureTypeCode.Int16 or SignatureTypeCode.UInt16=>(2,false),SignatureTypeCode.Int64 or SignatureTypeCode.UInt64 or SignatureTypeCode.Double=>(8,false),SignatureTypeCode.String or SignatureTypeCode.Object or SignatureTypeCode.TypeHandle or SignatureTypeCode.SZArray or SignatureTypeCode.Array=>(4,true),_=>(4,false)};}
 private static string Full(string ns,string name)=>string.IsNullOrEmpty(ns)?name:ns+"."+name;
}
